In [2]:
# ------------------ Pracice #1 ------------------
# https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [3]:
import torch
import numpy as np

In [6]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [20]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.2040, 0.1292],
        [0.6205, 0.7461]])



In [37]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.7385, 0.9589, 0.2248],
        [0.4033, 0.3078, 0.9899]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [38]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [59]:
# Question: Can I move the tensor to the gpu of the M1?
# Solution: https://stackoverflow.com/questions/68820453/how-to-run-pytorch-on-macbook-pro-m1-gpu

device = torch.device('cpu')
x = torch.rand((10000,10000), dtype =torch.float32)
y = torch.rand((10000,10000), dtype =torch.float32)
x = x.to(device)
y = y.to(device)

%timeit -n 100 -r 10 x * y

33.1 ms ± 1.9 ms per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [61]:
device = torch.device('mps')
x = torch.rand((10000,10000), dtype =torch.float32)
y = torch.rand((10000,10000), dtype =torch.float32)
x = x.to(device)
y = y.to(device)

%timeit -n 100 -r 10 x * y

19.1 ms ± 3.84 ms per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [62]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [67]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [68]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [79]:
# Matrix multiplication between two tensors, y1, y2, y3 has the same result

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

y1, y2, y3

(tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [81]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

z1, z2, z3

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]))

In [82]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [83]:
print(f"{tensor}")
tensor.add_(5)
print(f"{tensor}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [84]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
t: [1. 1. 1. 1. 1.]


In [86]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


In [88]:
n = np.ones(5)
t = torch.from_numpy(n)

In [89]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [90]:
# ------------------ Pracice #2 ------------------
# https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html

In [92]:
import torch
torch.manual_seed(1)

In [98]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matric
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2
T_data = [[[1., 2.], 
           [3., 4.]],
          [[5., 6.],
           [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [102]:
# Indexing into a vector
print(V[0])

# Indexing into a matricx
print(M[0])

# Indexing into a 3D tensor
print(T[0])

tensor(1.)
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [108]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-0.8262, -0.2221, -1.7949,  0.7299, -0.5619],
         [-0.1579,  1.5043, -1.3950,  0.5935,  0.3314],
         [-1.0592, -0.6280, -0.2713,  1.8469, -0.0313],
         [-0.0939, -1.6804,  1.3299,  0.1383,  1.0735]],

        [[ 0.4096, -1.5421, -1.0129, -0.0297,  1.2996],
         [ 0.4201,  2.4291,  1.3981, -0.6281,  1.1969],
         [ 0.6110, -0.4548,  1.3261,  0.5883, -1.2548],
         [ 1.3883, -0.4552,  0.3186, -0.3549,  0.6859]],

        [[ 0.8202, -0.1630, -0.8551, -0.7517, -0.0077],
         [ 2.6158, -0.0639,  0.2609,  1.2374, -1.5462],
         [ 0.7172,  0.7770,  0.4739,  0.9988, -0.1120],
         [-1.7404, -0.0340,  0.5267, -0.0861, -1.6190]]])


In [109]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [112]:
x_1 = torch.ones(2, 5)
y_1 = torch.zeros(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

x_2 = torch.ones(2, 3)
y_2 = torch.zeros(2, 5)
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.]])


In [113]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))

tensor([[[-0.7129, -0.0639,  1.0757, -0.5536],
         [-1.6160,  0.0934, -1.3898, -0.3105],
         [-0.3884, -0.0316, -0.5606, -0.6555]],

        [[ 0.7262,  0.6789, -0.4302, -0.3849],
         [-1.5083, -0.7200, -1.1910,  1.3271],
         [-2.1984,  0.2861, -0.2010, -2.5349]]])
tensor([[-0.7129, -0.0639,  1.0757, -0.5536, -1.6160,  0.0934, -1.3898, -0.3105,
         -0.3884, -0.0316, -0.5606, -0.6555],
        [ 0.7262,  0.6789, -0.4302, -0.3849, -1.5083, -0.7200, -1.1910,  1.3271,
         -2.1984,  0.2861, -0.2010, -2.5349]])


In [115]:
print(x.view(2, -1))

tensor([[-0.7129, -0.0639,  1.0757, -0.5536, -1.6160,  0.0934, -1.3898, -0.3105,
         -0.3884, -0.0316, -0.5606, -0.6555],
        [ 0.7262,  0.6789, -0.4302, -0.3849, -1.5083, -0.7200, -1.1910,  1.3271,
         -2.1984,  0.2861, -0.2010, -2.5349]])


In [119]:
x = torch.tensor([1., 2., 3.], requires_grad=True)

y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)

print(z.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [120]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [130]:
x.grad = None # without this line, it accummulates the grad
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [131]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)

print(x.requires_grad, y.requires_grad)
z = x + y
print(z.grad_fn)

False False
None


In [133]:
x = x.requires_grad_()
y = y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)

True


In [134]:
new_z = z.detach()
print(new_z.grad_fn)

None


In [137]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
